### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by amdxypf** [rockswang/qqcensorbot#3]
npm start报错。。怎么回事，大佬帮忙看下。
```
[root@centos qqcensorbot]# npm -v
5.6.0
[root@centos qqcensorbot]# node -v
v8.11.3
```
执行 npm start
```
> node index.js | node_modules\.bin\bunyan

sh: node_modules.binbunyan: command not found
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! qqcensorbot@1.0.0 start: `node index.js | node_modules\.bin\bunyan`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the qqcensorbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-20T15_49_52_766Z-debug.log

```

**Comment by rockswang** [comment]
你可以直接 node index.js启动，不过现在IOTQQ都改名OPQ了，而且迭代了很多版本了，这个项目很可能不能直接用了，仅供参考吧。
